# Generated by Django 4.2.5 on 2023-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tags',
            new_name='mainTopic',
        ),
        migrations.AddField(
            model_name='news',
            name='otherTopic',
            field=models.TextField(default=''),
        ),
    ]
