# Generated by Django 4.2.5 on 2023-09-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_tags_news_maintopic_news_othertopic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
