# Generated by Django 4.2.5 on 2023-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='articleBody',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='creationDate',
            field=models.DateField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='news',
            name='insertDate',
            field=models.DateField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='news',
            name='updateDate',
            field=models.DateField(default='', max_length=32),
        ),
    ]
