# Generated by Django 4.2.5 on 2023-09-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_articlebody_alter_news_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
