# Generated by Django 4.2.5 on 2023-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='articleBody',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='news',
            name='imageUrl',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='mainTopic',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='nTokens',
            field=models.SmallIntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='news',
            name='otherTopic',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='updateDate',
            field=models.DateField(blank=True, default='', max_length=32),
        ),
    ]
