# Generated by Django 4.2.5 on 2023-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_articlebody_alter_news_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creationDate',
            field=models.DateTimeField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='news',
            name='insertDate',
            field=models.DateTimeField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='news',
            name='updateDate',
            field=models.DateTimeField(blank=True, default='', max_length=32),
        ),
    ]
