# Generated by Django 4.2.5 on 2023-09-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_preprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='news',
            name='preprocessed',
            field=models.BooleanField(blank=0, default=False),
        ),
    ]
