# Generated by Django 4.2.5 on 2023-10-02 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_score_alter_news_preprocessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=255)),
                ('mediaUrl', models.CharField(default='', max_length=255)),
                ('insertDatetime', models.DateTimeField(default=django.utils.timezone.now, max_length=32)),
                ('statusCode', models.CharField(default='', max_length=5)),
            ],
            options={
                'db_table': 'garbage',
            },
        ),
        migrations.AddConstraint(
            model_name='garbage',
            constraint=models.UniqueConstraint(fields=('url', 'mediaUrl'), name='unique_news_url_combination'),
        ),
    ]
