# Generated by Django 4.2.1 on 2023-05-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='empty title', max_length=255)),
                ('subtitle', models.CharField(default='empty subtitle', max_length=255)),
                ('article', models.TextField(default='empty article')),
                ('source', models.CharField(default='empty source', max_length=255)),
                ('apiSource', models.CharField(default='empty api', max_length=255)),
                ('country', models.CharField(default='empty country', max_length=255)),
                ('creationDate', models.DateField(default='0000-01-01')),
                ('updateDate', models.DateField(default='1-1-1')),
                ('author', models.CharField(default='empty author', max_length=255)),
            ],
        ),
    ]
