# Generated by Django 4.2.1 on 2023-06-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_url',
            field=models.CharField(default='empty image', max_length=255),
        ),
    ]
