# Generated by Django 4.2.1 on 2023-05-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_noticia_indice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='indice',
            field=models.CharField(max_length=255),
        ),
    ]
